//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleDriveAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiLichThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoiLichThi()
        {
            this.ThongBaos = new HashSet<ThongBao>();
        }
    
        public int ID { get; set; }
        public string NgayTao { get; set; }
        public string HinhAnh { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> MaND { get; set; }
        public string MSND { get; set; }
        public Nullable<int> XetDuyet { get; set; }
        public Nullable<int> MaLich { get; set; }
        public Nullable<int> MaGV { get; set; }
        public string EmailGV { get; set; }
        public string HoTenSV { get; set; }
    
        public virtual LichThi LichThi { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
    }
}
