//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleDriveAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichThi()
        {
            this.DoiLichThis = new HashSet<DoiLichThi>();
        }
    
        public int MaLich { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<int> MaKhoa { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public Nullable<int> MaTG { get; set; }
        public Nullable<int> MaHT { get; set; }
        public Nullable<int> SLGV { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoiLichThi> DoiLichThis { get; set; }
        public virtual HinhThucThi HinhThucThi { get; set; }
        public virtual Khoa Khoa { get; set; }
        public virtual NhomMonHoc NhomMonHoc { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
        public virtual ThoiGian ThoiGian1 { get; set; }
    }
}
