//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleDriveAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHoc()
        {
            this.NhomMonHocs = new HashSet<NhomMonHoc>();
        }
    
        public int ID { get; set; }
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<int> MaKhoa { get; set; }
    
        public virtual Khoa Khoa { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhomMonHoc> NhomMonHocs { get; set; }
    }
}
