//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleDriveAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.DoiLichThis = new HashSet<DoiLichThi>();
            this.NhomMonHocs = new HashSet<NhomMonHoc>();
            this.ThongBaos = new HashSet<ThongBao>();
        }
    
        public int MaND { get; set; }
        public string TenND { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string SDT { get; set; }
        public Nullable<int> MaKhoa { get; set; }
        public Nullable<int> MaLND { get; set; }
        public string MSND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoiLichThi> DoiLichThis { get; set; }
        public virtual Khoa Khoa { get; set; }
        public virtual LoaiNguoiDung LoaiNguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhomMonHoc> NhomMonHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
    }
}
