//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleDriveAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhomMonHoc()
        {
            this.LichThis = new HashSet<LichThi>();
        }
    
        public int MaNhom { get; set; }
        public Nullable<int> MaMon { get; set; }
        public Nullable<int> MaGV { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> TenNhom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichThi> LichThis { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
